package genorm.test.orm;

/**
	This class has been automatically generated by GenORMous.  This file is for
	adding custom code to.  This file will not be regenerated once it exists.
	
*/
public class AllAuthorsData extends AllAuthorsQuery.Record
	{
	public AllAuthorsData(AllAuthorsQuery query, java.sql.ResultSet resultSet)
			throws java.sql.SQLException
		{
		query.super(resultSet);
		}
	}