package org.agileclick.genorm.test.orm;

/**
	This class has been automatically generated by GenORMous.  This file is for
	adding custom code to.  This file will not be regenerated once it exists.
	
*/
public class AllBooksData extends AllBooksQuery.Record
	{
	public AllBooksData(AllBooksQuery query, java.sql.ResultSet resultSet)
			throws java.sql.SQLException
		{
		query.super(resultSet);
		}
	}