/**
This file is automatically generated.  Do not modify
*/

package $package$.genorm;

import java.text.DecimalFormat;
import java.util.Locale;
import java.util.Map;
import java.util.StringTokenizer;

public class SQLQuery
	{
	protected Locale m_locale;
	protected Formatter m_formatter;
	
	public SQLQuery()
		{
		m_formatter = new DefaultFormatter();
		}
		
	public void setFormatter(Formatter formatter)
		{
		m_formatter = formatter;
		}
		
	public void setLocale(Locale locale)
		{
		m_formatter.setLocale(locale);
		}
		
	protected String replaceText(String input, Map<String, String> replacements)
		{
		String token = "%";
		StringBuilder sb = new StringBuilder();			
		StringTokenizer st = new StringTokenizer(input, token);
		String value;
		String s;
		int i = 0;
		boolean tag = false;
		
		while (st.hasMoreTokens())
			{
			s = st.nextToken();
			if ((value = (String)replacements.get(s)) != null)
				{
				tag = true;
				sb.append(value);
				}
			else
				{
				if ((i != 0)&&(!tag))
					sb.append(token);
				sb.append(s);
				tag = false;
				}
			i++;
			}
		
		return (sb.toString());
		}
	}
