group orm_object;

derivedSetAndGetMethods(col) ::= <<

//------------------------------------------------------------------------------
/**
	$col.comment$
*/
public $col.type$ get$col.methodName$() 
	{ 
	return (get$col.methodName$_base()); 
	}
	
public void set$col.methodName$($col.type$ id)
	{
	set$col.methodName$_base(id);
	}

$if(col.allowNull)$
public void set$col.methodName$Null()
	{
	set$col.methodName$Null_base();
	}
$endif$

>>

foreignGetAndSetMethods(foreignKeys) ::= <<

//------------------------------------------------------------------------------
public $foreignKeys.table.className$ get$foreignKeys.methodName$()
	{
	return (get$foreignKeys.methodName$_base());
	}
	
public void set$foreignKeys.methodName$($foreignKeys.table.className$ table)
	{
	set$foreignKeys.methodName$_base(table);
	}

>>

derivedClass(package,table,columns,foreignKeys) ::= <<
package $package$;

/**
	This class has been automatically generated by GenORMous.  This file is for
	adding custom code to.  This file will not be regenerated once it exists.
	
	$table.comment$
*/
public class $table.className$ extends $table.className$_base
	{
	
	}
>>
