group orm_object;

derivedSetAndGetMethods(col) ::= <<

//------------------------------------------------------------------------------
/**
	$col.comment$
*/
public $col.type$ get$col.methodName$() 
	{ 
	return (get$col.methodName$_base()); 
	}
	
public void set$col.methodName$($col.type$ id)
	{
	set$col.methodName$_base(id);
	}

>>

foreignGetAndSetMethods(foreignKeys) ::= <<

//------------------------------------------------------------------------------
public $foreignKeys.table.className$ get$foreignKeys.methodName$()
	{
	return (get$foreignKeys.methodName$_base());
	}
	
public void set$foreignKeys.methodName$($foreignKeys.table.className$ table)
	{
	set$foreignKeys.methodName$_base(table);
	}

>>

derivedClass(package,table,columns,foreignKeys) ::= <<
/*NOPRESERVE - Remove this comment to preserve this file from being overwritten
  by GenORMous.  This comment must be at the first of the file or else this file
  will not be regenerated.*/
package $package$;

/**
	This class has been automatically generated by GenORMous.  This file is for
	adding custom code to.  Once custom code has been added remove the comment
	from the top of the file.
	
	$table.comment$
*/
public class $table.className$ extends $table.className$_base
	{
	$columns:derivedSetAndGetMethods()$
	
	$foreignKeys:foreignGetAndSetMethods()$
	}
>>
